### ISSUE TITLE
Breaking changes are not referenced in module data

### ISSUE THREAD

**Issue by LaurentDardenne** [PowerShell/whatsnew#10]
### Know the breaking changes

Reading this:
_Get-WhatsNew is a cmdlet that provides information about changes and new features for a version of PowerShell, delivered to the local terminal experience._

It is impossible to know the changes (breaking change).
If I plan to port existing code to powershell 7 and above, I know what's new but I don't know what doesn't work like it used to.
```Powershell
Get-WhatsNew -version 6.0 | Select-String 'breaking'
# systems. Some of these are breaking changes, which also affect Windows. Others are only present or
#  Breaking changes
# We've introduced a number of breaking changes in PowerShell Core 6.0.
# To read more about them in detail, see [Breaking Changes in PowerShell Core 6.0][breaking-changes].
``` 
For this :
_"We've introduced a number of breaking changes in PowerShell Core 6.0."_
Ok, but which ones?

here https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-rc.2 we reference issue 5432
But the module datas does not reference this change
```Powershell
Get-WhatsNew -version 6.0 | Select-String '5432'
#no result
```
According to the RFC this case is not yet taken into account, but the text quoted at the beginning seems to contradict it.

.
.
 
I know it's not its purpose, but in a way this module addresses the management of release notes of different Microsoft products offering Powershell cmdlets:
SCCM
https://docs.microsoft.com/en-us/powershell/sccm/2103-release-notes?view=sccm-ps

Teams
https://docs.microsoft.com/en-us/MicrosoftTeams/teams-powershell-release-notes

Azure
https://docs.microsoft.com/en-us/powershell/azure/release-notes-azureps?view=azps-8.0.0

Having a common format for these releases notes impacting Powershell cmdlets would be a great help.

**Comment by theJasonHelmick** [comment]
@LaurentDardenne - Thank you for reporting this!  The 6.0 data included with Get-WhatsNew **is** missing the breaking changing information.  This information has been stored in a separate document because of its size of changes since Windows PowerShell 5.1.  This information will be included for the release - Thank you!
