### ISSUE TITLE
The content of `Get-WhatsNew` is not accurate

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/whatsnew#22]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

> ## Known issues in 7.3-preview.5
>
>These issues should be fixed in the next release of .NET 7 and included in a future preview of
PowerShell 7.3.
>
>- `Test-Connection` is broken due to an
>  [intentional breaking change](https://github.com/dotnet/runtime/issues/66746) in .NET 7. It's
>  tracked by [#17018](https://github.com/PowerShell/PowerShell/issues/17018)

This issue is not being actively worked on, so it likely won't make into the 7.3.

### Environment data

```PowerShell
PS:17> Get-Module Microsoft.PowerShell.WhatsNew

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     0.4.0                 Microsoft.PowerShell.WhatsNew       Get-WhatsNew
```
```


### Version

0.4.0

### Visuals

_No response_

**Comment by sdwheeler** [comment]
I am in the process of updating the release notes for Preview.7. I will include this fix.

**Comment by theJasonHelmick** [comment]
Thank you @daxian-dbw for reporting this.  This has been corrected in https://github.com/PowerShell/whatsnew/pull/26 and is expected to release soon as 0.4.1 on the PSGallery.
